<!DOCTYPE html>

<html lang="en"><head><meta charset="utf-8"/><meta content="width=device-width, initial-scale=1" name="viewport"/><script src="app-runtime.js?v=nz1.0-rc22-1"></script><script src="theme-config.js"></script><script src="trip-failure-runtime.js"></script><script src="asset-config.js"></script><script src="locale-config.js"></script><script src="geo-config.js?v=stage3-2h-port1"></script><script src="formatter.js"></script><script src="money-config.js"></script><script src="navigation-config.js?v=e2c-fullpage1"></script><script src="navigation.js?v=e2c-popup1"></script><script src="navigation-adapter.js?v=e2c-fullpage1"></script><script src="trip-config.js?v=stage3-2h-cert-final-fix1"></script><script src="storage-config.js?v=e2b-storage-isolation1"></script><script src="storage.js?v=e2b-storage-isolation1"></script><script src="storage-migration-runtime.js?v=e2b-storage-isolation1"></script><script src="sync-config.js?v=e2b-storage-isolation1"></script><script src="sync-runtime.js?v=stage3-2h-precert-data3"></script><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script><script src="supabase-client-runtime.js?v=nz1.0-rc22-1"></script><script src="expense-sync-runtime.js?v=e2b-storage-isolation1"></script><script src="moment-sync-runtime.js?v=e2b-storage-isolation1"></script><script src="generation-runtime.js?v=e2b-storage-isolation1"></script><script src="party-render-runtime.js?v=e2b-storage-isolation1"></script><script src="money.js"></script><title data-trip-page-title="Moments">Moments</title><meta content="" data-trip-theme-color="" name="theme-color"/><meta content="yes" name="apple-mobile-web-app-capable"/><meta content="" data-trip-apple-title="" name="apple-mobile-web-app-title"/><link data-trip-icon="icon192" rel="apple-touch-icon"/><link href="styles.css?v=e2c-fullpage1" rel="stylesheet"/></head><body class="moments-page"><nav class="site-nav"><a class="brand" href="index.html"><span class="brand-mark"><img alt="" data-brand-logo="header"/></span><span data-brand-text="navLabel"></span></a><button class="friend-pill" onclick="openFriendModal()"><span data-family="" data-friend-label=""></span></button></nav><main class="content-page"><div class="page-hero module-hero"><p class="kicker">MEMORY BOOK</p><h1>✨ Moments</h1><p class="lead">Keep the moments you’ll want to remember long after New Zealand.</p><div class="page-action-row moments-capture-choices" data-v35="moment-action">
<button class="btn primary-action" onclick="openMomentsModal('general')" type="button">✨ Just this moment</button>
<button class="btn moments-planned-entry" onclick="openPlannedMomentCapture()" type="button">📍 Planned activity</button>
</div></div><section class="prose-block"><h2>Saved Moments</h2><div id="momentsTimeline"></div></section></main><div class="mini-menu" id="daysMenu"></div><nav class="app-nav">
<a class="trip-trigger summary-link" href="trip.html"><span>🧳</span><small>Trip</small></a>
<a class="guide-trigger summary-link" href="guide.html"><span>📖</span><small>Guide</small></a>
<a class="days-trigger summary-link" href="itinerary.html"><span>🗓</span><small>Days</small></a>
<a class="summary-link" href="moments.html"><span>✨</span><small>Moments</small></a>
<a class="summary-link" href="expenses.html"><span>💸</span><small>Expenses</small></a>
</nav>
<script src="engine-integrity.js?v=nz1.0-rc22-1"></script><script src="data.js?v=stage3-2h-precert-data3"></script><script src="booking-authority.js?v=e2b-storage-isolation1"></script><script src="generation-selection-adapter.js?v=nz1.0-rc22-1"></script><script src="guide-navigation-runtime.js?v=stage3-2h-ownership1"></script><script src="itinerary-authority.js?v=e2b-storage-isolation1"></script><script src="core-runtime.js?v=e2b-storage-isolation1"></script><script src="expenses.js?v=stage3-2h-expense-cleanup1"></script><script src="moments.js?v=e2b-storage-isolation1"></script><script src="trip-runtime.js?v=e2c-fullpage1"></script><script src="moments-compat.js?v=stage3-2h-port1"></script><script src="script.js?v=stage3-2h-studio-guide-polish1"></script><script src="guide-runtime.js?v=e2c-fullpage1"></script><script src="admin.js?v=e2b-storage-isolation1"></script><script src="reset-runtime.js?v=e2b-storage-isolation1"></script><script src="publication-runtime.js?v=stage3-2h-port1"></script><script src="complete-runtime.js?v=stage3-2h-port1"></script><script src="export-runtime.js?v=stage3-2h-modal-cleanup1"></script><script src="currency-runtime.js?v=stage3-2h-front-interaction1-2"></script><script src="pwa.js?v=nz1.0-rc22-1"></script>


<div class="moments-modal" id="momentsModal"><div class="moments-sheet"><button class="moments-close" onclick="closeMomentsModal()" type="button">×</button><p class="kicker">MEMORY BOOK</p><h2 id="momentsTitle">Moment</h2><p class="lead modal-intro" id="momentsIntro">Add a rating, a short note and a photo at any stop. After the trip, this becomes the three families’ shared memory book.</p><p><span class="status-badge" id="momentsFriend">Friend</span> <button class="mini-btn" onclick="openFriendModal()">Change Family</button></p><div class="moments-form"><input id="momentsRating" type="hidden" value="0"/><div class="star-row"><span class="star" onclick="setStars(1)">⭐</span><span class="star" onclick="setStars(2)">⭐</span><span class="star" onclick="setStars(3)">⭐</span><span class="star" onclick="setStars(4)">⭐</span><span class="star" onclick="setStars(5)">⭐</span></div><p class="mood-help">Choose up to 2 moods</p><div class="mood-grid" id="moodGrid"></div><textarea id="momentsText" placeholder="Something to say..."></textarea><div class="photo-input">📷 Add Photo (Camera / Photo Library)</div><button class="btn" onclick="saveMoments()">Save</button></div></div></div>
<div class="unexpected-modal" id="unexpectedModal"><div class="unexpected-sheet"><button class="unexpected-close" onclick="closeUnexpectedModal()" type="button">×</button><p class="kicker">Moments</p><h2>Leave a Moment</h2><p class="lead">Add a rating, a short note and a photo at any stop. After the trip, this becomes the three families’ shared memory book.</p><p><span class="status-badge" id="unexpectedFriend">Friend</span></p><textarea id="unexpectedText" placeholder="Capture this moment..." style="width:100%;min-height:120px;border:1px solid var(--line);border-radius:18px;background:#fffaf2;padding:14px;font:inherit;color:var(--ink)"></textarea><div class="photo-input">📷 Add Photo (Camera / Photo Library)</div><button class="btn" onclick="saveUnexpected()">Save</button></div></div>
<div class="tools-modal" id="expenseModal"><div class="tools-sheet"><button class="tools-close" onclick="closeExpenseModal()" type="button">×</button><p class="kicker">TRIP EXPENSES</p><h2 id="expenseModalTitle">💸 What did we spend?</h2><p class="lead modal-intro" id="expenseIntro">Record each shared or personal expense. Personal Spend and Settlement update automatically.</p><div class="expense-form"><input id="expenseItem" placeholder="Item e.g. Family Dinner"/><input autocomplete="off" data-trip-currency-placeholder="" id="expenseTotal" inputmode="numeric" pattern="[0-9]*" placeholder="" type="tel"/><label>Paid by</label><select class="btn" data-party-options="" id="expensePaidBy" onchange="syncConsumedIfAuto()"></select><label class="check-row"><input id="expensePersonal" onchange="updateExpenseMode()" type="checkbox"/> Personal Expense</label><div id="splitBetweenBlock"><p>Split between</p><div class="expense-split-tools"><button class="mini-btn" onclick="splitAll()" type="button">Split between all</button><button class="mini-btn" onclick="clearAllSplit()" type="button">Clear all</button></div><div data-party-split-options=""></div></div><div id="consumedByBlock" style="display:none"><label>Consumed by <span class="timestamp">(same as paid by unless changed)</span></label><select class="btn" data-party-options="" id="expenseConsumedBy" onchange="markConsumedManual()"></select></div><br/><button class="btn" id="expenseSaveButton" onclick="saveExpense()">Save Expense</button></div><p class="timestamp">After saving, this window stays open so you can enter another expense. The summary updates when you close it.</p></div></div><div class="mama-modal" id="mamaModal"><div class="guide-sheet"><button class="mama-close" onclick="closeFriendModal()" type="button">×</button><p class="kicker">Family</p><h2>Choose Family</h2><div class="category-pop-list friend-choice-list" data-party-choices=""></div></div></div></body></html>
